### PR TITLE
fix: fixed timeouts for contributions fetch gql query

### LINKED ISSUE #21: Refactor contributors query
The GH Graphql [query](https://github.com/RedHat-Israel/red-hat-israel-site/blob/6d56452c067e972be40bc20b264019e139913a6e/_data/contributors.js#L27) we use for querying our members' contributions appears to be requesting a significant amount of data which causes GH API to time out.

### PR DESCRIPTION
**Pull request by TomerFi**
fixes: #21

Signed-off-by: Tomer Figenblat <tfigenbl@redhat.com>

### CODE REVIEW

**Comment by TomerFi** [comment]
@bennypowers

File: _data/contributors.js [hunk 1]
```diff
@@ -3,81 +3,91 @@ const { AssetCache } = require('@11ty/eleventy-fetch');
 const { graphql } = require('@octokit/graphql');
 
 const ORGANIZATION_NAME = 'RedHat-Israel'; // organization namespace
-const MAX_CONTRIBUTORS = 100; // modify this if/when we have more then 100 members
+const MAX_CONTRIBUTORS_FETCH = 20;
```
Comment (bennypowers) [inline _data/contributors.js]: maybe this can also go in the env, so that it has a lower number for dev and higher for prod?

File: _data/contributors.js [hunk 2]
```diff
@@ -3,81 +3,91 @@ const { AssetCache } = require('@11ty/eleventy-fetch');
...
-              hasAnyContributions
-              totalCommitContributions
-              totalIssueContributions
-              totalPullRequestContributions
-              totalPullRequestReviewContributions
-              totalRepositoryContributions
-            }
-            gists (first: 100) {
-              totalCount
+        membersWithRole(${members}) {
```
Comment (bennypowers) [inline _data/contributors.js]: now that we're here, perhaps this can be refactored to use GQL [variables](https://github.com/octokit/graphql.js#variables)? Then we could write this query in a .gql file instead of a template literal

**Review by bennypowers — APPROVED** [review]
LGTM. left some comments for possible improvements. merge or implement them as you like.

File: _data/contributors.js (hunk 1 above)
Comment (TomerFi) [reply _data/contributors.js]: @bennypowers 
we don't have a dev environment for gh api.

the limit for items per filter is 100, this was set to 20 because when higher, we risk gh internal timeout while fetching our items.
because of that high risk, and the fact that this is more of a system limitation that will rarely get modified, I'm not sure about exposing it as an environment variable.
WDYT?

Comment (bennypowers) [reply _data/contributors.js]: np

File: _data/contributors.js (hunk 2 above)
Comment (TomerFi) [reply _data/contributors.js]: @bennypowers 
Ok, I get the idea of using variables instead of template literals to avoid injection attacks,
good catch, I'll take care of that.
but I'm not following you on the _gql_ file usage, can you elaborate on that, please?

Comment (bennypowers) [reply _data/contributors.js]:
```ts
const query = await readFile(new URL('./contributors.query.gql', import.meta.url), 'utf8');

const result = await graphql({ query, variables, headers });
```

Comment (bennypowers) [reply _data/contributors.js]: writing gql in gql has a few advantages:
- syntax highlighting
- language server
- linting
- maintenance

Comment (TomerFi) [reply _data/contributors.js:46]: actually...
using variables will not work for us.

in the link you provided, the maintainer references the issue that caused him to recommend using variables instead of template literals, note his comment here, https://github.com/octokit/graphql.js/issues/2#issuecomment-445303444, and the last comment on the issue, he didn't do anything further then recomendending using variables, I guess dynamic queries has a more common usage.

we use _dynamic queries_, as he suggested, note this:
https://github.com/RedHat-Israel/red-hat-israel-site/blob/f9f0613f641733022c5f626deda1119bb3651693/_data/contributors.js#L24

and this:
https://github.com/RedHat-Israel/red-hat-israel-site/blob/f9f0613f641733022c5f626deda1119bb3651693/_data/contributors.js#L89

for each case, we pass a different set of filter properties, we do not have the `after` cursor value for the first run, just of the next runs, so using variables will not quite fit here I believe.

WDYT?

Comment (TomerFi) [reply _data/contributors.js]: > syntax highlighting
> language server
> linting
> maintenance

nice, it's a relatively small query so it's not such a big deal, but I'll look into it.
thanks.

Comment (TomerFi) [reply _data/contributors.js]: actually...
using variables is a bit tricky for us, as we use _dynamic queries_.

for the [first run](https://github.com/RedHat-Israel/red-hat-israel-site/blob/f9f0613f641733022c5f626deda1119bb3651693/_data/contributors.js#L22) of the query of we only use the `first` property, indicating how many members to fetch in this query:

```js
async function israelContributors(_configData) {
  const cache = new AssetCache('github_graphql_contributions');
  const summary = cache.isCacheValid('1d') ? cache.getCachedValue() : await getStatsForOrgMembers(`first: ${MAX_CONTRIBUTORS_FETCH}`);
  return {
    ...summary,
  };
}
```

any [other runs](https://github.com/RedHat-Israel/red-hat-israel-site/blob/f9f0613f641733022c5f626deda1119bb3651693/_data/contributors.js#L87) (runs dynamically based on the total members) require both the `first` and `after` properties, indicating how many members to fetch and what's the cursor value for the last member fetched:

```js
  if (result?.organization?.membersWithRole?.pageInfo?.hasNextPage) {
    return getStatsForOrgMembers(
      `first: ${MAX_CONTRIBUTORS_FETCH}, after: "${result.organization.membersWithRole.pageInfo.endCursor}"`,
      summary)
  }
```

so I think switching to using variables,
might require us to maintain 2 queries, whether it will be as a string or a _gql_ file.

not only that, but I'm not sure _gpl_ files play well with dynamic queries.
I'll have to look a bit more into that, and even if it does, well that brings us back to the fear of injection attacks exploding our dynamic queries.

I think that for this specific query and the way it's constructed, meaning, we use hard-coded data for constructing dynamic queries, so for leveraging injection attack, you need to modify the code and not its variables, so I'm not sure we have anything to worry about, and I don't think maintaining two almost identical queries for that is worth it.

but... if you think otherwise, I'll be happy to implement this.

WDYT?

Comment (TomerFi) [reply _data/contributors.js]: @bennypowers 
I pushed a new commit to demonstrate my point, I can revert it if you don't like it.

1. I got to admit, I like the idea of using variables instead of template literals, it makes the code a bit more readable and cleaner I think.

2. in regards to, _syntax highlighting_, _language server_, and _linting_, I'm using _vscode_ with [this graphql extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql), turns out I simply needed to add a comment "_#graphql_" in the query, and I got everything working. I can still move the queries into _gql_ files if you prefer it that way.

3. in regards to _maintenance_, as explained above, we now have two "almost-identical" queries to maintain, if we opt to outsource them into _gql_ files, then we have to keep it that way, if we opt to keep them as strings, then I can perhaps play around with them a bit and combined them into 1 query concatenated at runtime, but then we're back where we started, template literals.

Please advise on the next step,
I'm ok with leaving this as it is after the last commit (using variables + 2 queries).

Comment (TomerFi) [reply _data/contributors.js]: BTW

I'm thinking of tweaking the max members fetch from _20_ to _15_,
I was starting to view timeouts with 20 as well.

Comment (TomerFi) [reply _data/contributors.js]: In the last commit, I moved the shared attributed for both queries in a fragment, which reduces the maintenance levels back down.

Comment (bennypowers) [reply _data/contributors.js]: Yeah I was thinking a fragment would be good
Might require some trickery to get it into a gql file, which I still think is better then template literals, but if you're itching to merge we can do that later

Comment (TomerFi) [reply _data/contributors.js]: I did the fragment thing in the last commit, only I did it using variables (using some template literals) instead of files.
I think it looks good and should work well for what we're doing, we now have 2 small "query" variables leveraging 1 "fragment" variable.

check it out: https://github.com/RedHat-Israel/red-hat-israel-site/blob/fix-contributors-query-timeouts/_data/contributors.js#L16

Comment (bennypowers) [reply _data/contributors.js]: jumped in with a few small changes, namely file loading. its [not ideal](https://github.com/octokit/graphql.js/issues/331) but its ok for now
